# Etapa 1 — Builder
FROM node:20 AS builder
WORKDIR /app

COPY package*.json ./
RUN npm install

COPY tsconfig.json ./
COPY src ./src

# Compila TypeScript
RUN npm run build

# Etapa 2 — Runtime
FROM node:20 AS production
WORKDIR /app

COPY package*.json ./
RUN npm install --only=production

# Copia os arquivos compilados
COPY --from=builder /app/dist ./dist

EXPOSE 3000

CMD ["node", "dist/server.js"]
